/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// export {}

// declare global {
//   const ILocalMoon: typeof import("~icons/local/moon.jsx")["default"];
//   const ILocalSun: typeof import("~icons/local/sun.jsx")["default"];
// }
// // for type re-export
// declare global {
//   // @ts-ignore
//   export type { ReactNode } from "react";
// }
